#!/bin/bash

java \
--module-path ~/Downloads/javafx-sdk-11.0.2/lib \
--add-modules javafx.controls,javafx.fxml \
--add-exports javafx.graphics/com.sun.javafx.sg.prism=ALL-UNNAMED \
-jar ./build/libs/xox.jar